create table user_table
(
    id       integer generated by default as identity
        primary key,
    email    varchar(255)
        unique,
    password varchar(255),
    username varchar(255)
);



create table account_table
(
    balance double precision not null,
    user_id integer          not null
        unique
        constraint fk4peoirph6e93334pu0elhluya
            references user_table,
    id      bigint generated by default as identity
        primary key
);


create table transaction_table
(
    amount      double precision,
    fee         double precision,
    id          integer generated by default as identity
        primary key,
    receiver_id integer
        constraint fkivtpa6o75tehsk7ydqosws42h
            references user_table,
    sender_id   integer
        constraint fk9yh9p683gvua4i5ibqm3kv9u3
            references user_table,
    description varchar(255)
);


create table user_friends
(
    friend_id      integer not null
        constraint fk9mfdk05xvej445vy9ycmuoseo
            references user_table,
    user_entity_id integer not null
        constraint fkqdyqtqd5b3o2frro7x006a8j2
            references user_table
);
